"""Rebuild the README leaderboard and its two cost plots from ``results/**/*.json``.

Every chapter run writes one results JSON (schema 1, docs/DESIGN.md §7). This script turns those files
into the public scoreboard, so it also enforces the reporting rules from CONTRIBUTING.md:

* every success rate is shown with its Wilson 95% interval;
* the cost column is the *improvement* budget: every robot-minute except the ``eval`` category
  (search + train). The final held-out evaluation is not counted, but search episodes always are,
  so a method cannot hide its search;
* runs on a task variant other than ``v1`` say so next to the robot (``so101 (hard)``), runs scored on
  an older init-set version are tagged, and Δ is shown only when base and final share their episodes;
* hardware rows show counts (``30/30``), never a bare "100%";
* runs made with ``--quick`` (CI smoke tests) are left out, because they are not real results.

Usage:

    uv run python tools/leaderboard.py              # table into README.md, plots into media/leaderboard/
    uv run python tools/leaderboard.py --no-plots   # table only

It needs only the standard library and matplotlib, so it runs without MuJoCo or torch.
"""

from __future__ import annotations

import argparse
import itertools
import json
import math
import os
import re
import sys
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
START, END = "<!-- LEADERBOARD:START -->", "<!-- LEADERBOARD:END -->"
COLUMNS = [
    "Chapter",
    "Method",
    "Robot",
    "Setting",
    "Base SR [CI]",
    "Final SR [CI]",
    "Δ",
    "Improvement robot-min",
    "Human-min",
    "n eval",
]
NUMERIC_FROM = 4  # columns from here on are right-aligned
INIT_SET_VERSION = "v1"  # must match lastmile.common.eval.INIT_SET_VERSION (checked by the tests)
PLOT_FILES = {"robot": "success_vs_robot_minutes.png", "human": "success_vs_human_minutes.png"}
# A log axis cannot show 0. Zero-cost runs (common: most sim runs use no human time) are drawn at this
# floor with a hollow marker, which is the same as plotting log10(cost + epsilon) for them.
COST_FLOOR_MIN = 0.01  # minutes (0.6 s)
NOTE = (
    "*Generated by `tools/leaderboard.py` from `results/**/*.json`; do not edit by hand. "
    "SR = success rate on the recorded init set with its Wilson 95% interval. "
    "Plots include all listed runs, including exploratory and ablation rows; chapter docs identify the headlines. "
    "Improvement robot-min = search + train rollouts (the final evaluation is not counted). "
    "A robot shown as `so101 (hard)` ran a task variant other than v1. "
    "Hardware rows show k/n, never a bare 100%.*"
)


@dataclass
class Rate:
    """A success rate as reported in a results file."""

    sr: float
    ci: tuple[float, float] | None
    k: int | None
    n: int | None
    init_set: str | None
    init_set_version: str | None = None


@dataclass
class Run:
    """One results JSON, reduced to what the leaderboard shows."""

    path: Path
    chapter: str
    method: str
    robot: str
    variant: str
    setting: str
    base: Rate | None
    final: Rate
    robot_minutes: float | None  # improvement budget: everything but "eval" (None if the file has no budget)
    human_minutes: float | None


def wilson(k: int, n: int, z: float = 1.96) -> tuple[float, float]:
    """Wilson score interval for k successes in n trials.

    Kept local (rather than imported from lastmile.common.eval) so this tool has no heavy dependencies.
    Unlike the naive p ± z·sqrt(p(1-p)/n), it stays inside [0, 1] and does not collapse to zero width
    at 0/n or n/n: 30/30 gives [0.886, 1.0], not [1.0, 1.0].
    """
    if n <= 0:
        return (0.0, 1.0)
    p = k / n
    denom = 1 + z**2 / n
    center = (p + z**2 / (2 * n)) / denom
    half = z * math.sqrt(p * (1 - p) / n + z**2 / (4 * n**2)) / denom
    return (max(0.0, center - half), min(1.0, center + half))


def parse_rate(d: dict) -> Rate:
    """Read ``{"sr", "ci", "k", "n", "init_set"}``; any of them may be missing if the rest imply it."""
    if not isinstance(d, dict):
        raise TypeError("success-rate entry is not an object")
    k, n = d.get("k"), d.get("n")
    sr = d.get("sr")
    if sr is None and k is not None and n:
        sr = k / n
    if sr is None:
        raise ValueError("no success rate (need 'sr' or 'k' and 'n')")
    sr = float(sr)
    if not 0.0 <= sr <= 1.0:
        raise ValueError(f"success rate {sr} is outside [0, 1]")
    ci = d.get("ci")
    if ci is not None:
        lo, hi = (float(x) for x in ci)
        ci = (lo, hi)
    elif k is not None and n:
        ci = wilson(int(k), int(n))
    return Rate(sr, ci, None if k is None else int(k), None if n is None else int(n), d.get("init_set"),
                d.get("init_set_version"))


def role_suffix(data: dict) -> str:
    """Label rows a chapter did not choose as its result, so an ablation never reads like the headline."""
    role = (data.get("extra") or {}).get("role") if isinstance(data.get("extra"), dict) else None
    return f" ({role})" if role and role != "chosen" else ""


def parse_run(path: Path, data: object) -> Run:
    """Validate one results file; raise ValueError or TypeError if it cannot be used."""
    if not isinstance(data, dict):
        raise TypeError("top level is not an object")
    if data.get("schema", 1) != 1:
        raise ValueError(f"unsupported schema {data.get('schema')!r}")
    for key in ("chapter", "method", "final"):
        if key not in data:
            raise ValueError(f"missing required field '{key}'")
    setting = str(data.get("setting", "sim"))
    final = parse_rate(data["final"])
    if setting == "real" and not (final.k is not None and final.n):
        raise ValueError("a hardware result must report k and n, so its interval can be shown")
    budget = data.get("budget") or {}
    robot = budget.get("robot_minutes")
    human = budget.get("human_minutes")
    return Run(
        path=path,
        chapter=str(data["chapter"]),
        method=str(data["method"]) + role_suffix(data),
        robot=str(data.get("robot", "so101")),
        variant=str(data.get("variant", "v1")),
        setting=setting,
        base=parse_rate(data["base"]) if data.get("base") else None,
        final=final,
        robot_minutes=None if robot is None else float(sum(v for c, v in robot.items() if c != "eval")),
        human_minutes=None if human is None else float(sum(human.values())),
    )


def is_quick_run(data: object) -> bool:
    """True for CI smoke runs (``--quick``), which must never reach the scoreboard."""
    config = data.get("config") if isinstance(data, dict) else None
    return isinstance(config, dict) and config.get("quick") is True


def load_runs(results_dir: Path) -> list[Run]:
    """Read every results JSON under ``results_dir``, skipping (with a warning) files we cannot use."""
    runs = []
    for path in sorted(results_dir.rglob("*.json")):
        try:
            data = json.loads(path.read_text())
            if is_quick_run(data):
                print(f"leaderboard: leaving out {path} (a --quick smoke run)", file=sys.stderr)
                continue
            run = parse_run(path, data)
            version = run.final.init_set_version
            if version is not None and version != INIT_SET_VERSION:
                print(f"warning: {path} was scored on init sets {version!r}, not the current "
                      f"{INIT_SET_VERSION!r}; its row is tagged", file=sys.stderr)
            runs.append(run)
        except (OSError, ValueError, TypeError, AttributeError) as err:
            print(f"warning: skipping {path}: {err}", file=sys.stderr)
    return runs


# ---------------------------------------------------------------- table


def _chapter_key(chapter: str) -> tuple[float, str]:
    """Sort ch2 before ch10 (natural order), and unnumbered chapters last."""
    match = re.search(r"\d+", chapter)
    return (int(match.group()) if match else math.inf, chapter)


def _pct(x: float) -> str:
    return f"{100 * x:.1f}"


def format_rate(rate: Rate | None, setting: str) -> str:
    """``41.0% [35.2, 47.1]`` in sim; ``27/30 [74.4, 96.5]`` on hardware, where n is small."""
    if rate is None:
        return "—"
    if setting == "real" and rate.k is not None and rate.n:
        head = f"{rate.k}/{rate.n}"
    else:
        head = f"{_pct(rate.sr)}%"
    return head if rate.ci is None else f"{head} [{_pct(rate.ci[0])}, {_pct(rate.ci[1])}]"


def format_minutes(minutes: float | None) -> str:
    if minutes is None:
        return "n/a"
    if minutes == 0:
        return "0"
    return f"{minutes:.2f}" if minutes < 1 else f"{minutes:,.1f}"


def is_paired(base: Rate, final: Rate) -> bool:
    """True if base and final were scored on the same episodes, as far as the file tells."""
    same_set = base.init_set is None or final.init_set is None or base.init_set == final.init_set
    same_n = base.n is None or final.n is None or base.n == final.n
    return same_set and same_n


def table_row(run: Run) -> list[str]:
    if run.chapter == "ch00":
        delta = "— (builds base_v1)"  # the base is the demonstrator being imitated, not a policy being improved
    elif run.base is None:
        delta = "—"
    elif not is_paired(run.base, run.final):
        delta = "n/a (unpaired)"  # a difference between different episode sets is not an improvement
    else:
        delta = f"{100 * (run.final.sr - run.base.sr):+.1f} pp"
    n_eval = "?" if run.final.n is None else str(run.final.n)
    tags = [run.final.init_set] if run.final.init_set and run.final.init_set != "eval" else []
    version = run.final.init_set_version
    if version is not None and version != INIT_SET_VERSION:
        tags.append(f"init sets {version}")
    if tags:
        n_eval += f" ({', '.join(tags)})"
    return [
        run.chapter,
        run.method,
        run.robot if run.variant == "v1" else f"{run.robot} ({run.variant})",
        run.setting,
        format_rate(run.base, run.setting),
        format_rate(run.final, run.setting),
        delta,
        format_minutes(run.robot_minutes),
        format_minutes(run.human_minutes),
        n_eval,
    ]


def build_table(runs: list[Run]) -> str:
    """Markdown table sorted by chapter, then task variant (v1 first), then final success (best first)."""
    align = [":---" if i < NUMERIC_FROM else "---:" for i in range(len(COLUMNS))]
    lines = ["| " + " | ".join(COLUMNS) + " |", "| " + " | ".join(align) + " |"]
    if not runs:
        message = (
            "*No results yet: run an `algos/NN_*.py` script (it writes `results/<chapter>/*.json`), "
            "then `make leaderboard`.*"
        )
        lines.append("| — | " + message + " |" + " |" * (len(COLUMNS) - 2))
    def order(r: Run) -> tuple:
        return (_chapter_key(r.chapter), r.variant != "v1", r.variant, -r.final.sr, r.method)

    for run in sorted(runs, key=order):
        lines.append("| " + " | ".join(cell.replace("|", "\\|") for cell in table_row(run)) + " |")
    return "\n".join(lines)


def render_block(runs: list[Run], plots: list[Path], readme: Path) -> str:
    """Everything that goes between the README markers: the table, a note, and links to the plots."""
    parts = [build_table(runs), "", NOTE]
    for plot in plots:
        rel = Path(os.path.relpath(plot, readme.resolve().parent)).as_posix()
        parts += ["", f"![{plot.stem.replace('_', ' ')}]({rel})"]
    return "\n".join(parts)


def update_readme(readme: Path, block: str) -> bool:
    """Put ``block`` between the markers, adding them at the end if missing. Returns True if changed."""
    old = readme.read_text() if readme.exists() else ""
    section = f"{START}\n{block}\n{END}"
    has_start, has_end = START in old, END in old
    if has_start and has_end and old.index(START) < old.index(END):
        pattern = re.compile(re.escape(START) + ".*?" + re.escape(END), re.DOTALL)
        new = pattern.sub(lambda _: section, old, count=1)  # a function, so "\|" in the table stays literal
    elif has_start or has_end:
        raise ValueError(
            f"{readme} has only one leaderboard marker, or they are out of order; fix it by hand"
        )
    else:
        new = (old.rstrip() + "\n\n" if old.strip() else "") + "## Leaderboard\n\n" + section + "\n"
    if new == old:
        return False
    readme.write_text(new)
    return True


# ---------------------------------------------------------------- plots

SURFACE, INK, MUTED, GRID = "#fcfcfb", "#0b0b0b", "#898781", "#e1e0d9"
SETTING_COLORS = {"sim": "#2a78d6", "real": "#eb6834"}  # two hues only: a scatter stays CVD-safe


def _label_heights(xs: list[float], ys: list[float], gap: float = 4.0) -> list[float]:
    """Push labels of points at (nearly) the same x apart vertically so they do not overprint.

    Zero-cost runs all sit at the floor, so this matters in practice. Labels only move down, by at
    least ``gap`` percentage points from the label above; a leader line then ties each one to its point.
    """
    heights = list(ys)
    order = sorted(range(len(xs)), key=lambda i: (round(math.log10(xs[i]) / 0.15), -ys[i]))
    for prev, cur in itertools.pairwise(order):
        if abs(math.log10(xs[cur]) - math.log10(xs[prev])) < 0.15:
            heights[cur] = min(ys[cur], heights[prev] - gap)
    return heights


def _draw_panel(ax, runs: list[Run], costs: list[float | None], xlabel: str, labels: bool = True) -> None:
    """One point per run: final success with its Wilson interval against a cost on a log axis.

    ``labels=False`` drops the per-point method names, for panels with too many runs to label legibly.
    """
    points = [(run, cost) for run, cost in zip(runs, costs) if cost is not None]
    ax.set_xscale("log")
    ax.set_ylim(0, 104)
    ax.axhline(95, color=MUTED, lw=1, zorder=1)
    ax.annotate(
        "95%\ntarget",
        (1, 95),
        xycoords=("axes fraction", "data"),
        xytext=(4, 0),
        textcoords="offset points",
        va="center",
        fontsize=7.5,
        color=MUTED,
    )
    if not points:
        ax.set_xlim(COST_FLOOR_MIN / 2, 100)
        ax.text(0.5, 0.5, "No results yet", transform=ax.transAxes, ha="center", va="center", color=MUTED)
    xs = [max(cost, COST_FLOOR_MIN) for _, cost in points]
    ys = [100 * run.final.sr for run, _ in points]
    for (run, cost), x, y, label_y in zip(points, xs, ys, _label_heights(xs, ys)):
        color = SETTING_COLORS.get(run.setting, MUTED)
        lo, hi = run.final.ci if run.final.ci else (run.final.sr, run.final.sr)
        ax.errorbar(
            x,
            y,
            yerr=[[max(0.0, y - 100 * lo)], [max(0.0, 100 * hi - y)]],
            fmt="o",
            ms=8,
            color=color,
            mfc=SURFACE if cost <= 0 else color,
            mec=color,
            mew=1.8,
            elinewidth=1.2,
            capsize=3,
            zorder=3,
        )
        if not labels:
            continue
        leader = None if label_y == y else {"arrowstyle": "-", "color": MUTED, "lw": 0.6}
        ax.annotate(
            f"{run.chapter} {run.method}" + ("" if run.variant == "v1" else f" ({run.variant})"),
            (x, y),
            xytext=(x * 1.35, label_y),
            textcoords="data",
            va="center",
            fontsize=7.5,
            color=INK,
            arrowprops=leader,
            zorder=4,
        )
    if xs and labels:  # unlabelled panels share one x range, which the caller sets
        ax.set_xlim(COST_FLOOR_MIN / 2, max(100.0, 20 * max(xs)))  # room for the labels on the right
    if any(cost <= 0 for _, cost in points):
        ax.axvline(COST_FLOOR_MIN, color=MUTED, lw=1, ls=":", zorder=1)
        ax.annotate(
            "zero cost\n(hollow, drawn here)",
            (COST_FLOOR_MIN, 2),
            xytext=(4, 0),
            textcoords="offset points",
            fontsize=7.5,
            color=MUTED,
        )
    ax.set_xlabel(xlabel, color=INK)
    ax.set_ylabel("Final success, % (Wilson 95% CI)", color=INK)
    ax.grid(True, which="major", color=GRID, lw=0.8)
    ax.set_axisbelow(True)
    for side in ("top", "right"):
        ax.spines[side].set_visible(False)
    for side in ("left", "bottom"):
        ax.spines[side].set_color(MUTED)
    ax.tick_params(colors=MUTED, labelcolor=INK, labelsize=8)
    handles = [
        ax.plot([], [], "o", ms=8, color=SETTING_COLORS[s], label=s)[0]
        for s in SETTING_COLORS
        if any(r.setting == s for r, _ in points)
    ]
    if len(handles) > 1:
        ax.legend(handles=handles, frameon=False, fontsize=8, loc="lower right")


MAX_LABELLED = 12  # up to this many runs, one labelled panel; beyond it, one unlabelled panel per chapter


def save_plots(runs: list[Run], out_dir: Path) -> list[Path]:
    """Write the two leaderboard plots and return their paths.

    With a handful of runs each point carries its name. Once there are more than ``MAX_LABELLED``, the
    names would overprint, so the plot becomes small multiples: one panel per chapter, shared axes, no
    per-point names (the table above the plots names every run).
    """
    from matplotlib.figure import Figure  # no pyplot: no GUI backend or global state needed

    out_dir.mkdir(parents=True, exist_ok=True)
    panels = [
        ("robot", "Improvement robot-minutes (search + train), log scale", lambda r: r.robot_minutes),
        ("human", "Human-minutes, log scale", lambda r: r.human_minutes),
    ]
    paths = []
    for key, xlabel, cost_of in panels:
        n = sum(cost_of(r) is not None for r in runs)
        title = f"Final success vs {key}-minutes ({n} run{'s' if n != 1 else ''})"
        if n <= MAX_LABELLED:
            fig = Figure(figsize=(7.5, 4.5), dpi=150, facecolor=SURFACE)
            ax = fig.subplots()
            ax.set_facecolor(SURFACE)
            _draw_panel(ax, runs, [cost_of(r) for r in runs], xlabel)
            ax.set_title(title, loc="left", fontsize=10, color=INK)
        else:
            chapters = sorted({r.chapter for r in runs}, key=_chapter_key)
            ncols = min(3, len(chapters))
            nrows = math.ceil(len(chapters) / ncols)
            fig = Figure(figsize=(4.2 * ncols, 3.4 * nrows), dpi=150, facecolor=SURFACE)
            axes = fig.subplots(nrows, ncols, sharex=True, sharey=True, squeeze=False).ravel()
            costs = [c for r in runs if (c := cost_of(r)) is not None]
            hi = max([100.0, *(3 * c for c in costs)])
            for ax, chapter in zip(axes, chapters):
                mine = [r for r in runs if r.chapter == chapter]
                ax.set_facecolor(SURFACE)
                ax.set_xscale("log")
                ax.set_xlim(COST_FLOOR_MIN / 2, hi)  # fixed before drawing: no autoscaling to a single point
                _draw_panel(ax, mine, [cost_of(r) for r in mine], xlabel, labels=False)
                m = sum(cost_of(r) is not None for r in mine)
                ax.set_title(f"{chapter} ({m} run{'s' if m != 1 else ''})", loc="left", fontsize=9, color=INK)
            for i, ax in enumerate(axes):
                if i >= len(chapters):
                    ax.set_visible(False)
                    continue
                if i % ncols:
                    ax.set_ylabel("")
                if i < len(chapters) - ncols:
                    ax.set_xlabel("")
            fig.suptitle(title, x=0.01, ha="left", fontsize=10, color=INK)
            fig.tight_layout()
        path = out_dir / PLOT_FILES[key]
        fig.savefig(path, bbox_inches="tight", facecolor=SURFACE)
        paths.append(path)
    return paths


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--root",
        type=Path,
        default=REPO_ROOT,
        help="repository root that holds results/ and media/ (default: this repo)",
    )
    parser.add_argument(
        "--readme", type=Path, default=None, help="README to update (default: <root>/README.md)"
    )
    parser.add_argument("--no-plots", action="store_true", help="only rewrite the table")
    args = parser.parse_args(argv)

    runs = load_runs(args.root / "results")
    plot_dir = args.root / "media" / "leaderboard"
    if not args.no_plots:
        save_plots(runs, plot_dir)
    plots = [p for p in (plot_dir / name for name in PLOT_FILES.values()) if p.exists()]
    readme = args.readme or args.root / "README.md"
    try:
        changed = update_readme(readme, render_block(runs, plots, readme))
    except ValueError as err:
        print(f"error: {err}", file=sys.stderr)
        return 1
    print(f"leaderboard: {len(runs)} run(s); {readme} {'updated' if changed else 'already up to date'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
